// Mock data for local development (when API is not available)

import type { MonthlyDashboardData, ClosurePlanWithDetails, AllocationRecommendation } from '../types';

export const mockDashboardData: MonthlyDashboardData = {
  yearMonth: '2026-01',
  year: 2026,
  month: 1,
  monthName: 'Jan',
  totalCapacity: 8500,
  totalOccupied: 7200,
  totalAvailable: 1300,
  closuresThisMonth: [],
  sites: [
    {
      siteId: 'site_S1',
      siteCode: 'S1',
      siteName: 'ABS',
      regionCode: 'RIYADH',
      regionName: 'Riyadh',
      status: 'ACTIVE',
      totalCapacity: 519,
      totalOccupied: 358,
      totalAvailable: 161,
      utilizationPercent: 69,
      riskStatus: 'OK',
      floors: [
        {
          floorId: 'floor_S1F02',
          floorCode: 'F02',
          floorName: '12',
          totalCapacity: 95,
          totalOccupied: 0,
          totalAvailable: 95,
          utilizationPercent: 0,
          riskStatus: 'OK',
          zones: [
            {
              zoneId: 'zone_S1F02Z02',
              zoneCode: 'Z02',
              zoneName: 'A',
              siteFloorZoneCode: 'S1F02Z02',
              capacity: 95,
              occupied: 0,
              available: 95,
              utilizationPercent: 0,
              riskStatus: 'OK',
              isClosing: true,
              closureDate: '2026-04-01',
            },
          ],
        },
        {
          floorId: 'floor_S1F03',
          floorCode: 'F03',
          floorName: '18',
          totalCapacity: 169,
          totalOccupied: 155,
          totalAvailable: 14,
          utilizationPercent: 92,
          riskStatus: 'WARNING',
          zones: [
            {
              zoneId: 'zone_S1F03Z03',
              zoneCode: 'Z03',
              zoneName: 'A',
              siteFloorZoneCode: 'S1F03Z03',
              capacity: 169,
              occupied: 155,
              available: 14,
              utilizationPercent: 92,
              riskStatus: 'WARNING',
              isClosing: true,
              closureDate: '2026-04-01',
            },
          ],
        },
        {
          floorId: 'floor_S1F04',
          floorCode: 'F04',
          floorName: '19',
          totalCapacity: 255,
          totalOccupied: 203,
          totalAvailable: 52,
          utilizationPercent: 80,
          riskStatus: 'OK',
          zones: [
            {
              zoneId: 'zone_S1F04Z04',
              zoneCode: 'Z04',
              zoneName: 'A',
              siteFloorZoneCode: 'S1F04Z04',
              capacity: 255,
              occupied: 203,
              available: 52,
              utilizationPercent: 80,
              riskStatus: 'OK',
              isClosing: true,
              closureDate: '2026-04-01',
            },
          ],
        },
      ],
    },
    {
      siteId: 'site_S2',
      siteCode: 'S2',
      siteName: 'Crystal Plaza',
      regionCode: 'RIYADH',
      regionName: 'Riyadh',
      status: 'ACTIVE',
      totalCapacity: 1539,
      totalOccupied: 1131,
      totalAvailable: 408,
      utilizationPercent: 73,
      riskStatus: 'OK',
      floors: [],
    },
    {
      siteId: 'site_S3',
      siteCode: 'S3',
      siteName: 'Dammam',
      regionCode: 'EASTERN',
      regionName: 'Eastern Province',
      status: 'ACTIVE',
      totalCapacity: 258,
      totalOccupied: 251,
      totalAvailable: 7,
      utilizationPercent: 97,
      riskStatus: 'RISK',
      floors: [],
    },
    {
      siteId: 'site_S4',
      siteCode: 'S4',
      siteName: 'HUR',
      regionCode: 'RIYADH',
      regionName: 'Riyadh',
      status: 'ACTIVE',
      totalCapacity: 500,
      totalOccupied: 450,
      totalAvailable: 50,
      utilizationPercent: 90,
      riskStatus: 'WARNING',
      floors: [],
    },
    {
      siteId: 'site_S8',
      siteCode: 'S8',
      siteName: 'New HUR',
      regionCode: 'RIYADH',
      regionName: 'Riyadh',
      status: 'ACTIVE',
      totalCapacity: 346,
      totalOccupied: 135,
      totalAvailable: 211,
      utilizationPercent: 39,
      riskStatus: 'OK',
      floors: [],
    },
    {
      siteId: 'site_S10',
      siteCode: 'S10',
      siteName: 'RHQ',
      regionCode: 'RIYADH',
      regionName: 'Riyadh',
      status: 'ACTIVE',
      totalCapacity: 2102,
      totalOccupied: 2075,
      totalAvailable: 27,
      utilizationPercent: 99,
      riskStatus: 'RISK',
      floors: [],
    },
    {
      siteId: 'site_S12',
      siteCode: 'S12',
      siteName: 'Smart',
      regionCode: 'RIYADH',
      regionName: 'Riyadh',
      status: 'ACTIVE',
      totalCapacity: 1502,
      totalOccupied: 1502,
      totalAvailable: 0,
      utilizationPercent: 100,
      riskStatus: 'RISK',
      floors: [],
    },
    {
      siteId: 'site_S13',
      siteCode: 'S13',
      siteName: 'UAE',
      regionCode: 'UAE',
      regionName: 'United Arab Emirates',
      status: 'ACTIVE',
      totalCapacity: 86,
      totalOccupied: 63,
      totalAvailable: 23,
      utilizationPercent: 73,
      riskStatus: 'OK',
      floors: [],
    },
    {
      siteId: 'site_S14',
      siteCode: 'S14',
      siteName: 'Warsaw',
      regionCode: 'EUROPE',
      regionName: 'Europe',
      status: 'ACTIVE',
      totalCapacity: 70,
      totalOccupied: 0,
      totalAvailable: 70,
      utilizationPercent: 0,
      riskStatus: 'OK',
      floors: [],
    },
  ],
};

export const mockClosures: ClosurePlanWithDetails[] = [
  {
    id: 'cp_S1F02Z02',
    zoneId: 'zone_S1F02Z02',
    siteName: 'ABS',
    siteCode: 'S1',
    floorName: '12',
    zoneName: 'A',
    siteFloorZoneCode: 'S1F02Z02',
    regionCode: 'RIYADH',
    closureDate: '2026-04-01',
    yearMonth: '2026-04',
    seatsAffected: 95,
    status: 'PLANNED',
    allocations: [],
    totalAllocated: 0,
    unseatedStaff: 95,
  },
  {
    id: 'cp_S1F03Z03',
    zoneId: 'zone_S1F03Z03',
    siteName: 'ABS',
    siteCode: 'S1',
    floorName: '18',
    zoneName: 'A',
    siteFloorZoneCode: 'S1F03Z03',
    regionCode: 'RIYADH',
    closureDate: '2026-04-01',
    yearMonth: '2026-04',
    seatsAffected: 155,
    status: 'PLANNED',
    allocations: [],
    totalAllocated: 0,
    unseatedStaff: 155,
  },
  {
    id: 'cp_S1F04Z04',
    zoneId: 'zone_S1F04Z04',
    siteName: 'ABS',
    siteCode: 'S1',
    floorName: '19',
    zoneName: 'A',
    siteFloorZoneCode: 'S1F04Z04',
    regionCode: 'RIYADH',
    closureDate: '2026-04-01',
    yearMonth: '2026-04',
    seatsAffected: 203,
    status: 'PLANNED',
    allocations: [],
    totalAllocated: 0,
    unseatedStaff: 203,
  },
  {
    id: 'cp_S5F24Z24',
    zoneId: 'zone_S5F24Z24',
    siteName: 'MP1',
    siteCode: 'S5',
    floorName: '1st',
    zoneName: 'A',
    siteFloorZoneCode: 'S5F24Z24',
    regionCode: 'RIYADH',
    closureDate: '2026-06-30',
    yearMonth: '2026-06',
    seatsAffected: 113,
    status: 'PLANNED',
    allocations: [],
    totalAllocated: 0,
    unseatedStaff: 113,
  },
];

export const mockAllocationRecommendations: AllocationRecommendation[] = [
  {
    targetSiteId: 'site_S8',
    targetSiteName: 'New HUR',
    targetRegion: 'Riyadh',
    isSameRegion: true,
    availableCapacity: 211,
    recommendedAllocation: 211,
    newUtilization: 100,
    riskStatus: 'RISK',
    isEditable: true,
  },
  {
    targetSiteId: 'site_S2',
    targetSiteName: 'Crystal Plaza',
    targetRegion: 'Riyadh',
    isSameRegion: true,
    availableCapacity: 408,
    recommendedAllocation: 242,
    newUtilization: 89,
    riskStatus: 'WARNING',
    isEditable: true,
  },
  {
    targetSiteId: 'site_S14',
    targetSiteName: 'Warsaw',
    targetRegion: 'Europe',
    isSameRegion: false,
    availableCapacity: 70,
    recommendedAllocation: 0,
    newUtilization: 0,
    riskStatus: 'OK',
    isEditable: true,
  },
  {
    targetSiteId: 'site_S13',
    targetSiteName: 'UAE',
    targetRegion: 'United Arab Emirates',
    isSameRegion: false,
    availableCapacity: 23,
    recommendedAllocation: 0,
    newUtilization: 73,
    riskStatus: 'OK',
    isEditable: true,
  },
];
